language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

env:
  - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

php:
  - 7.1
  - 7.2

install:
 - composer update $COMPOSER_FLAGS --prefer-dist

script: vendor/bin/phpunit
