language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

matrix:
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable"
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable"
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"

install:
 - composer update $COMPOSER_FLAGS --prefer-dist

script:
 - vendor/bin/phpunit
 - vendor/bin/phpcs -n
