language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

env:
  global:
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - script: vendor/bin/phpcs -n
      php: 7.2
      env: PHPCS_BUILD=1

install:
 - composer update $COMPOSER_FLAGS --prefer-dist

script:
 - vendor/bin/phpunit
